### ISSUE TITLE
 Task :processDebugMainManifest FAILED - Godot 3.5.3

### ISSUE THREAD

**Issue by mmicoe** [201949/godot-google-play-billing-7#1]
Hi, 
first of all, thank you very much for your plugin.

I get an issue on build project: (Godot 3.5.3)

`> Task :processDebugMainManifest FAILED
/Users/uegos/ATractor/android/build/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [GodotGooglePlayBilling-6.2.1-release.aar] /Users/mmicoe/.gradle/caches/transforms-3/63bde9d34ca10326008a47380c609545/transformed/jetified-GodotGooglePlayBilling-6.2.1-release/AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.magikelle.godotgoogleplaybilling" to force usage (may lead to runtime failures)

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [GodotGooglePlayBilling-6.2.1-release.aar] /Users/mmicoe/.gradle/caches/transforms-3/63bde9d34ca10326008a47380c609545/transformed/jetified-GodotGooglePlayBilling-6.2.1-release/AndroidManifest.xml as the library might be using APIs not available in 19
  	Suggestion: use a compatible library with a minSdk of at most 19,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.magikelle.godotgoogleplaybilling" to force usage (may lead to runtime failures)

`

1. Updating config.gradle -> minSdk : 19, to minSdk: 21 -> does not working
2. tools:overrideLibrary on manifest -> does not working

I'm sure there is a simple solution. Can you tell me how to fix this?

SOLVED:
Updating MinSDK to 21 in min export window (custo_build/min_sdk) works fine!!!!!!

All the best,
Mauro

**Comment by 201949** [comment]
Hello Mauro,

Thank you for your interest in the plugin. Currently, transitioning to the updated version of the Google Play Billing Library in Godot 3.5 is causing issues for many users. However, I have managed to implement a plugin using Google Play Billing Library version 6.2.1, which will be supported until August 2025.

Regarding the error you are encountering:

1. First, check the export template settings for Android. You need to specify a minimum SDK version of 21 there.
2. Secondly, check the \android\build\config.gradle file and make the necessary changes to the SDK version specification if needed.

I am attaching screenshots for your reference.

![изображение](https://github.com/201949/godot-google-play-billing-6/assets/70590729/aa3a2889-3bee-43f9-be1c-372c3dc675ca)

![изображение](https://github.com/201949/godot-google-play-billing-6/assets/70590729/30146e41-1d66-4574-8354-4777494662b3)

Additionally, I would like to add that several projects built in Godot 3.5.2 for the Android platform using this plugin have successfully passed all checks and are now available on Google Play.

Best regards,
Mike, from Magikelle Studio

**Comment by 201949** [comment]
Was not an issue.
