### ISSUE TITLE
Update to 3.6

### ISSUE THREAD

**Issue by ehmprah** [201949/godot-google-play-billing-7#11]
The plugin is working nicely for 3.5.2, but I haven't been able to update the godot library to a different version. Is there a chance of an release any time soon? If not, could I have some pointers as to how to update the dependency?

**Comment by 201949** [comment]
Hello, @ehmprah 

if you want to 
change this section of build.gradle app level from this: compileOnly 'org.godotengine:godot:3.5.2.stable'
to path to different version of Godot library
For example:
Download the necessary library, for example this one:https://github.com/godotengine/godot/releases/download/3.6-stable/godot-lib.3.6.stable.release.aar library

**Comment by 201949** [comment]
Hello, @ehmprah

if you want to use a different version of the Godot library to build the plugin, then place it in the root of the cloned repository and change this app level section of `build.gradle`
from this: `compileOnly 'org.godotengine:godot:3.5.2.stable'`
to this: `compileOnly fileTree(dir: '..', include: ['godot-lib*.aar'])`

***For example:***
1. Clone plugin repository from Github
2. Download the necessary library, for example this one:
[godot-lib.3.6.stable.release.aar](https://github.com/godotengine/godot/releases/download/3.6-stable/godot-lib.3.6.stable.release.aar)
3. Put Godot library in plugin`s root directory
4. Change app level `build.gradle`
5. Build plugin from CLI with "gradlew build" command or in Android Studio instead

And you will have a plugin for the Godot library you need

P.S.: To build the plugin, I used dependencies from the central maven repository so as not to download the necessary Godot libraries every time. But unfortunately in the maven repository the latest version of the libraries for Godot 3.5.x is 3.5.2.stable

[Maven Godot Repository](https://repo.maven.apache.org/maven2/org/godotengine/godot/)

***Added later:***
As a fun experiment, I tried specifying downloading a Godot library file directly from Github. Here's the code for `build.gradle`:
```gradle
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "de.undercouch:gradle-download-task:5.6.0"
  }
}

plugins {
    id 'com.android.library'
}

apply plugin: 'de.undercouch.download'

ext.godotLibRelease = "stable.release.aar" // For 4.x might be "stable.template_release.aar"
ext.godotLibReleaseVersion = "3.6" // Godot lib version
ext.libraryName = "GodotGooglePlayBilling"
ext.libraryVersionCode = 2
ext.libraryVersionName = "6.2.1"

android {
    namespace 'com.magikelle.godotgoogleplaybilling'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode libraryVersionCode
        versionName libraryVersionName
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "$libraryName-$libraryVersionName-${variant.name}.aar"
        }
    }
}

task downloadAarFile(type: Download) {
    src "https://github.com/godotengine/godot/releases/download/$godotLibReleaseVersion-stable/godot-lib.$godotLibReleaseVersion.$godotLibRelease"
    dest file("../libs/godot-lib.$godotLibReleaseVersion.$godotLibRelease")
}

preBuild.dependsOn downloadAarFile

dependencies {
    compileOnly fileTree(dir: '../libs', include: ['godot-lib*.aar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.android.billingclient:billing:6.2.1'
}
```
In essence, this is the same as simply downloading the library file and manually putting it in the directory with the plugin sources. But the experience is interesting, in my opinion.

I hope everything worked out for you.

**Comment by ehmprah** [comment]
This worked like a charm, the "compileOnly fileTree(...)" was the magic I was missing. 

Thanks for the quick help and your outstanding work on this plugin, @201949!
