### ISSUE TITLE
I need for Godot 4.3

### ISSUE THREAD

**Issue by wargaming0009** [201949/godot-google-play-billing-7#12]
Hi do you have  google play billing 6 for godot 4.3?

**Comment by 201949** [comment]
Hi @wargaming0009,

Yes, my plugin also works in Godot 4.3, but at the moment I have not prepared a corresponding release. However, you can rebuild my plugin for the Godot 4.3 library. In this case, you will need to make some changes to your `gdscript` singleton to match the correct syntax of the new Godot 4.3 version.

If you need a working plugin for the Godot 4.X branch, try using the following plugin:
[AndroidIAPP Godot Plugin](https://github.com/code-with-max/godot-google-play-iapp) by @code-with-max

Hope this helps you.
