### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by dgsdestinygamestudios** [201949/godot-google-play-billing-7#3]
How can we handle subs? With the library Remi had, we could use the same way for "subs" and "inapp". With yours, "inapp" works fine, purchasing "subs" crashes the app.

**Comment by 201949** [comment]
> How can we handle subs? With the library Remi had, we could use the same way for "subs" and "inapp". With yours, "inapp" works fine, purchasing "subs" crashes the app.

Hi,

Regarding the handling of subscriptions, I'm pleased to inform you that in my version of the plugin, I've already addressed this issue and released an update. Now, both 'inapp' and 'subs' purchases are handled seamlessly without causing app crashes. Thank you for your patience and understanding. You can access the updated release at this link: [Release 6.2.1 with subs](https://github.com/201949/godot-google-play-billing-6/releases/tag/6.2.1_subs)

**Comment by 201949** [comment]
Fixed

**Comment by dgsdestinygamestudios** [comment]
Thank you for responding. Example code has one issue though. You query SUBSCRIPTION_ITEMS as "inapp" in "_on_connected" callback. Changing it to the following fixes the issue.

func _on_connected():
	print("CONNECTED!")
	yield(get_tree().create_timer(2), "timeout") # Wait for 2 seconds
	# Request product details for all items
	var all_items = NON_CONSUMABLE_ITEMS + CONSUMABLE_ITEMS
	payment.queryProductDetails(all_items, "inapp")
	payment.queryProductDetails(SUBSCRIPTION_ITEMS, "subs")
	# Query information about purchased items
	payment.queryPurchases("inapp")
	payment.queryPurchases("subs")

**Comment by 201949** [comment]
Thank you for your feedback. I have made the suggested corrections.

**Comment by 201949** [comment]
> Thank you for responding. Example code has one issue though. You query SUBSCRIPTION_ITEMS as "inapp" in "_on_connected" callback. Changing it to the following fixes the issue.
> 
> func _on_connected(): print("CONNECTED!") yield(get_tree().create_timer(2), "timeout") # Wait for 2 seconds # Request product details for all items var all_items = NON_CONSUMABLE_ITEMS + CONSUMABLE_ITEMS payment.queryProductDetails(all_items, "inapp") payment.queryProductDetails(SUBSCRIPTION_ITEMS, "subs") # Query information about purchased items payment.queryPurchases("inapp") payment.queryPurchases("subs")

Thank you for your feedback. I have made the suggested corrections.
